### ISSUE TITLE
Not sure how to select a path

### ISSUE THREAD

**Issue by gruijter** [smeans/pjxml#2]
Great that you made this module! I was using xml2js before, but needed something lightweight for simple stuff. But I'm running into problems with a device that spits out xml that is probably not fully compliant to the xml standards.

In below xml example I'm trying to select everything from m:GetInfoResponse with:
```
const el = doc.select('//m:GetInfoResponse*');
```
But the result is not making much sense because it somehow includes 'soap-env:Envelope', which I definitely cannot use:

```
Node {
  type: 9,
  content:
   [ '',
     Node { type: 7, content: [Array] },
     '',
     Node {
       type: 1,
       content: [],
       name: 'soap-env:Envelope',
       attributes: [Object] },
     '/Description>        ',
```

So how can I solve this?

Thankx for your help!

```
<?xml version="1.0" encoding="UTF-8"?>
<soap-env:Envelope
        xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/"
        soap-env:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
        >
<soap-env:Body>
    <m:GetInfoResponse
        xmlns:m="urn:NETGEAR-ROUTER:service:DeviceInfo:1">
        <ModelName>R7000</ModelName>
        <Description>Netgear Smart Wizard 3.0, specification 0.7 version</Description>
        <SerialNumber>3LG23B7106783</SerialNumber>
        <Firmwareversion>V1.0.9.12</Firmwareversion>
        <SmartAgentversion>3.0</SmartAgentversion>
        <FirewallVersion>ACOS NAT-Netfilter v3.0.0.5 (Linux Cone NAT Hot Patch 06/11/2010)</FirewallVersion>
        <VPNVersion>N/A</VPNVersion>
        <OthersoftwareVersion>1.2.23</OthersoftwareVersion>
        <Hardwareversion>R7000</Hardwareversion>
        <Otherhardwareversion>N/A</Otherhardwareversion>
        <FirstUseDate>Saturday, 20 Feb 2016 23:40:20</FirstUseDate>
    </m:GetInfoResponse>
    <ResponseCode>000</ResponseCode>
</soap-env:Body>
</soap-env:Envelope>
```

**Comment by gruijter** [comment]
bump. any feedback / news on this? I have had to revert to the xml2json module :(

**Comment by smeans** [comment]
Sorry, I'm just seeing this for the first time. Without running your test case, my guess it it has something to do with the trailing * in your selector. Good luck!

**Comment by smeans** [comment]
There was actually a parsing bug that caused your document to be parsed incorrectly! I just pushed a fix, thanks for letting me know about it! #
